### ISSUE TITLE
download while on AWS creates one file

### ISSUE THREAD

**Issue by itcarroll** [earthaccess-dev/earthaccess#562]
The `earthaccess.download` function appears to be (over)writing all data received to a single file, rather than to separate files in the provided directory, when working on AWS. This example uses earthaccess 0.9.0 on cryointhecloud.

```python
import earthaccess

earthaccess.login()
results = earthaccess.search_data(short_name="PACE_OCI_L2_AOP_NRT", count=2)
earthaccess.download(results, "test")
!ls -l test
```
```
Granules found: 4148
 Getting 2 granules, approx download size: 0.07 GB
Accessing cloud dataset using dataset endpoint credentials: https://obdaac-tea.earthdatacloud.nasa.gov/s3credentials
Downloaded: test/PACE_OCI.20240409T203648.L2.OC_AOP.V1_0_0.NRT.nc
Downloaded: test/PACE_OCI.20240409T204148.L2.OC_AOP.V1_0_0.NRT.nc
-rw-r--r-- 1 jovyan jovyan 9516948 May  8 21:04 test
```
Instead of a "test" folder, I get one "test" file.

Expected behavior would be either to `raise "STAHP! Wut R u DoINg?"` or just download the files.

**Comment by chuckwondo** [comment]
@itcarroll, I suspect this is not specific to cryointhecloud.

You likely need to first create the target directory (I don't know if it will be created for you, which may be the problem). Delete the erroneous file, create the `test` directory, then try again.

If that still doesn't work, then in addition, specify `"test/"` instead of simply `"test"` in your call to `download`.

Please report back your findings. Whatever your findings, this appears to be behavior that we must correct (and likely clearly document as well).

**Comment by itcarroll** [comment]
Oh, I should have mentioned that the function works as documented, even creating the directory if it doesn't exist, without direct access.

**Comment by chuckwondo** [comment]
> Oh, I should have mentioned that the function works as documented, even creating the directory if it doesn't exist, without direct access.

Oh, very interesting. Would you mind trying my suggestions above, just to see if/how things are affected in that environment, just so we have more information about how things work/don't work?

**Comment by mfisher87** [comment]
>Oh, I should have mentioned that the function works as documented, even creating the directory if it doesn't exist, without direct access.

:eyes: Good catch!!!

**Comment by itcarroll** [comment]
> > Oh, I should have mentioned that the function works as documented, even creating the directory if it doesn't exist, without direct access.
> 
> Oh, very interesting. Would you mind trying my suggestions above, just to see if/how things are affected in that environment, just so we have more information about how things work/don't work?

Creating the folder first causes expected behavior (i.e. multiple files in the folder). Using "test/" as the argument is equivalent to "test".

It's possible, based on fsspec's `get()` [documentation](https://filesystem-spec.readthedocs.io/en/latest/api.html#fsspec.spec.AbstractFileSystem.get), that a fix could be changing [store.py#L574](https://github.com/nsidc/earthaccess/blob/0869be7cd4d2ffad33588da4c2b9e77d9d70d085/earthaccess/store.py#L574) to
```
s3_fs.get(file, str(local_path) + "/")
```
although that's a bit flimsy looking.

**Comment by chuckwondo** [comment]
> > > Oh, I should have mentioned that the function works as documented, even creating the directory if it doesn't exist, without direct access.
> > 
> > 
> > Oh, very interesting. Would you mind trying my suggestions above, just to see if/how things are affected in that environment, just so we have more information about how things work/don't work?
> 
> Creating the folder first causes expected behavior (i.e. multiple files in the folder). Using "test/" as the argument is equivalent to "test".
> 
> It's possible, based on fsspec's `get()` [documentation](https://filesystem-spec.readthedocs.io/en/latest/api.html#fsspec.spec.AbstractFileSystem.get), that a fix could be changing [store.py#L574](https://github.com/nsidc/earthaccess/blob/0869be7cd4d2ffad33588da4c2b9e77d9d70d085/earthaccess/store.py#L574) to
> 
> ```
> s3_fs.get(file, str(local_path) + "/")
> ```
> 
> although that's a bit flimsy looking.

Cool. Would you mind trying one more test? Delete the files in the `test` dir and also remove the dir again, so it doesn't exist. Then try downloading with `"test/"` as the argument. I want to see if including the trailing slash will then cause fsspec to create the directory for you.

**Comment by itcarroll** [comment]
If a "test" folder exists, download works with "test" and "test/". If there is nothing called "test", one file called "test" is created for either argument.

Conversion to `pathlib.Path` and back to `str` seems like it eliminates the slash: `str(pathlib.Path("test/"))` is just `test`.

**Comment by chuckwondo** [comment]
After a bit of digging into fsspec, I see the problem, which boils down to this: _either_ the local (destination) directory must _exist_ (and be a directory) OR the specified path must _include a trailing slash_.

**Comment by itcarroll** [comment]
That all checks out with my understanding, and I like the explicit fix. Thanks!

I don't know what the MAAP is, but perhaps you are also hitting #444.

**Comment by chuckwondo** [comment]
> That all checks out with my understanding, and I like the explicit fix. Thanks!
> 
> I don't know what the MAAP is, but perhaps you are also hitting #444.

Sorry, FYI, here's MAAP: https://maap-project.org/

I suspect I'm indeed hitting #444.
