### ISSUE TITLE
Automatically add comment to PR that requires maintainer to review and rerun integration tests

### ISSUE THREAD

**Issue by chuckwondo** [earthaccess-dev/earthaccess#824]
As a follow-on to [Allow maintainers to run integration tests on PR from a fork](https://github.com/nsidc/earthaccess/pull/818#top), it would be very convenient to enhance the GitHub integration-tests workflow to post a comment to the PR when it requires a maintainer to perform a security review and re-run the tests, and the comment should include a link to the GitHub page for the failed integration tests build, where the maintainer can then click the "Rerun" button.

While a maintainer can currently see failed builds and navigate to them to hit the Rerun button, adding a comment to the PR would make the needed action visible in the PR itself.

**Comment by itcarroll** [comment]
Is this fixed? If I understand correctly, the fix ought to have resulted in a bot comment on #909, right?

**Comment by mfisher87** [comment]
This isn't working as expected. The bot comments are going in the wrong PR! https://github.com/nsidc/earthaccess/issues/922
